name: tests
on: [push]
jobs:
  run:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Java  
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.4'
          java-package: jdk
      - name: Run tests
        run: |
          ./gradlew test
          ./gradlew jacocoTestReport
      - name: Upload coverage to gist
        run: |
          ./gradlew parseJacocoReport
          ./gradlew createGistPayload
          curl -H "Authorization: token ${{ secrets.GIST_TOKEN }}" \
               -H "Content-Type: application/json" \
               -X PATCH \
               --data @build/gist.json https://api.github.com/gists/2741eb65fdb9bdee723e50d7648294ed
